########################################
#                                      #
#        Astro Tech Development        #
#                                      #
########################################

########################################
#                                      #
#       Important Configuration        #
#                                      #
########################################
Token:
MongoDBURL:
Prefix:
  - "."
  - "-"
  - "`"
  - "="
  - "?"

########################################
#                                      #
#        General Configuration         #
#                                      #
########################################
ServerName: Astro Tech
ServerColor: 33D458
GuildID: "864243948867158046"
